# Generated by Django 3.0.8 on 2020-08-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploadapp', '0001_initial'),
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialestudio',
            name='blob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploadapp.File'),
        ),
        migrations.AddField(
            model_name='materialestudio',
            name='clases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Clases'),
        ),
        migrations.AddField(
            model_name='evaluaciones',
            name='materias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Materias'),
        ),
        migrations.AddField(
            model_name='evaluaciones',
            name='subida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Subidas'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Grados'),
        ),
        migrations.AddField(
            model_name='entregas',
            name='ejercios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Ejercicios'),
        ),
        migrations.AddField(
            model_name='entregas',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Estudiantes'),
        ),
        migrations.AddField(
            model_name='entregas',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Evaluaciones'),
        ),
        migrations.AddField(
            model_name='entregas',
            name='subida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Subidas'),
        ),
        migrations.AddField(
            model_name='entregas',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Tareas'),
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='clases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Clases'),
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='subida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Subidas'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='estudiante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Estudiantes'),
        ),
        migrations.AddField(
            model_name='clases',
            name='materias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Materias'),
        ),
        migrations.AddField(
            model_name='clases',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Profesores'),
        ),
    ]
