# Generated by Django 3.0.8 on 2020-08-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_auto_20200806_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('estudiante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Estudiantes')),
            ],
        ),
    ]
