# Generated by Django 3.0.8 on 2020-08-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_userlms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
