# Generated by Django 3.0.8 on 2020-08-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0004_auto_20200813_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregas',
            name='upp',
            field=models.IntegerField(default=0),
        ),
    ]
