# Generated by Django 3.0.8 on 2020-08-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0005_entregas_upp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
