# Generated by Django 3.0.5 on 2020-08-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0006_tareas_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subidas',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
