# Generated by Django 3.0.5 on 2020-08-29 03:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0007_auto_20200827_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subidas',
            name='fecha',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 8, 29, 3, 59, 23, 855856, tzinfo=utc)),
        ),
    ]
