# Generated by Django 3.0.5 on 2020-08-29 04:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0008_auto_20200828_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subidas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 4, 6, 19, 17080, tzinfo=utc)),
        ),
    ]
