# Generated by Django 3.0.5 on 2020-08-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0009_auto_20200828_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subidas',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
