# Generated by Django 3.0.5 on 2020-09-08 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0010_auto_20200828_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.Estudiantes'),
        ),
    ]
